// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdjxymxgjglleqznlzxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkanh5bXhnamdsbGVxem5senhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0OTkxMzYsImV4cCI6MjA5MDA3NTEzNn0.EN25xcCruiqCZjcwVdmI-cEK18QyS36xgaf3UeB-O7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});